LTI Auth API calls
rifflearning/mattermost-redux pull request #1
Opened 2019-01-23 14:42 UTC by chetanyakan

#### Summary
- Add actions and API calls for user signup API.

#### Checklist
- [x] Ran `make check-style` to check for style errors (required for all pull requests)
- [x] Ran `make test` to ensure unit tests passed
- [x] Ran `make flow` to ensure type checking passed

2019-01-23 16:08 UTC, dcalacci requested changes
This looks good! But I have one question/concern -- we've generally been making any changes to redux behavior within the `mattermost-webapp` repo, rather than inside of `mattermost-redux`. These would be the first changes we make to the redux repo, and I would like to avoid doing that if we can. 

Do you think these could be added to the local redux state in `mattermost-webapp`, or is there a really solid reason to keep them within `mattermost-redux`?

2019-01-23 17:44 UTC, mlippert commented
@dcalacci Particularly as we are thinking that these changes may end up being contributed back to the mattermost project, it makes sense for the changes to be made in the normal mattermost development way.

2019-01-23 19:34 UTC, mlippert approved these changes

2019-01-23 19:34 UTC, merged

2019-01-24 00:48 UTC, mlippert commented
![](https://github.trello.services/images/mini-trello-icon.png) [Merge and deploy Sprint 2 PRs](https://trello.com/c/qw3IXkMK/21-merge-and-deploy-sprint-2-prs)